### PR TITLE
Updated to support TypeScript v1.0.1

### PR DESCRIPTION
**Pull request by NathanielInman**
Now supports the newest version of TypeScript by supplying ScriptSnapshot, getSyntacticDiagnostics, and other new compilation requirement methods introduced to the TypeScript library. Added the variable scripts to keep track of the number of scripts being pulled and fire the compiler after the number of loaded scripts reaches the total number of scripts. Also now allows support for older IE as XHR request was failing on IE7-9. It wasn't previously waiting until the scripts were completely loaded sometimes before pushing them into the src and requesting compile. Pulled the script tag scraper out of the compiler and ran it in an anonymous function to initiate the loading of the content before firing the compiler.

### CODE REVIEW

**Comment by niutech** [comment]
Thanks a lot! I will check the code and then merge it.

**Comment by smartboyathome** [comment]
Any status on this?

**Comment by boussou** [comment]
Any status on this? ;-b)
This is awesome work guys.

**Comment by markwylde** [comment]
Any status on this? Great work niutech and Nathan!

#6

**Comment by NathanielInman** [comment]
Abandoned repo, closing my PR.

**Pull request closed without merging**
